# Generated by Django 5.2.7 on 2025-10-24 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_song_artist_song_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
