# Generated by Django 5.2.7 on 2025-10-24 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_album_created_date_artist_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
