# Generated by Django 5.2.7 on 2025-10-25 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_artist_name_alter_song_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='songs', to='catalog.category'),
        ),
    ]
